from flask_restful import reqparse, abort, Api, Resource
from flask import jsonify


models = [
            {
            'id':1,
            'company':'Acorns',
            'name': 'Conservative',
            'JPST': 20,
            'ICSH': 20,
            'SHV': 20,
            'BIL': 20,
            'GBIL':20,
            'fees':.0013,
            },
        
          {   
              'id':2,
            'company':'Acorns',
            'name': 'Moderately Conservative',
            'VOO': 24,
           'VNQ': 4,
           'LQD': 30,
           'VB': 4,
           'SHY': 30,
           'VEA': 8,
           'fees':.0011,
        },

        {   'id':3,
            'company':'Acorns',
            'name': 'Moderate',
            'VOO': 29,
            'VWO': 3,
           'VNQ': 6,
           'LQD': 20,
           'VB': 10,
           'SHY': 20,
           'VEA': 12,
            'fees':.0009,
        },
  

            {
            'id':4,   
            'company':'Acorns',
            'name': 'Moderately Aggressive',
            'VOO': 38,
            'VWO': 4,
           'VNQ': 8,
           'LQD': 10,
           'VB': 14,
           'SHY': 10,
           'VEA': 16,
           'fees':.0007,
        },

        {   'id':5,
            'company':'Acorns',
            'name': 'Aggressive',
            'VOO': 40,
            'VWO': 10,
           'VNQ': 10,   
           'VB': 20,
           'VEA': 20,
           'fees':.0005,
        },
        

        {   'id':6,
            'company':'BlackRock',
            'name': '0/100  (Equity / Fixed Income %)',
            'LQD': 24,
            'IGSB': 12,
            'GOVT': 24,   
            'NEAR': 21,
            'SHYG': 9,
            'TLT':1,
            'EMB':5,
            'HYG':4,
            'fees':.002,
        },

        {   'id':7,
            'company':'BlackRock',
            'name': '10/90  (Equity / Fixed Income %)',
            'IVV':5,
            'ESGU':2,
            'EFG':2,
            'USMV':2,
            'LQD': 24,
            'IGSB': 12,
            'GOVT': 18,   
            'NEAR': 19,
            'SHYG': 9,
            'TLT':1,
            'EMB':4,
            'HYG':2,
            'fees':.0019,
        },

        {   'id':8,
            'company':'BlackRock',
            'name': '20/80  (Equity / Fixed Income %)',
            'IVV':9,
            'ESGU':3,
            'EFG':2,
            'ESGE':3,
            'VLUE':2,
            'USMV':2,
            'LQD': 21,
            'IGSB': 12,
            'GOVT': 19,   
            'NEAR': 14,
            'SHYG': 9,
            'TLT':1,
            'EMB':3,
            'fees':.0017,
            
        },

        {   'id':9,
            'company':'BlackRock',
            'name': '30/70  (Equity / Fixed Income %)',
            'IVV':14,
            'ESGU':4,
            'EFG':3,
            'ESGE':4,
            'VLUE':2,
            'IXN':2,
            'USMV':2,
            'LQD': 17,
            'IGSB': 11,
            'GOVT': 18,   
            'NEAR': 12,
            'SHYG': 7,
            'TLT':1,
            'EMB':3,
            'fees':.0017,
            
        },

        {   'id':10,
            'company':'BlackRock',
            'name': '40/60  (Equity / Fixed Income %)',
            'IVV':18,
            'ESGU':4,
            'EFG':5,
            'ESGE':5,
            'VLUE':3,
            'IXN':2,
            'IHI':2,
            'USMV':2,
            'LQD': 15,
            'IGSB': 11,
            'GOVT': 15,   
            'NEAR': 9,
            'SHYG': 6,
            'TLT':1,
            'EMB':2,
            'fees':.0017,
            
        },

        {   'id':11,
            'company':'BlackRock',
            'name': '50/50  (Equity / Fixed Income %)',
            'IVV':21,
            'ESGU':9,
            'EFG':6,
            'ESGE':6,
            'VLUE':3,
            'IXN':2,
            'IHI':2,
            'USMV':2,
            'LQD': 15,
            'IGSB': 11,
            'GOVT': 10,   
            'NEAR': 6,
            'SHYG': 6,
            'TLT':1,
            'fees':.0016,
            
        },

        {   'id':12,
            'company':'BlackRock',
            'name': '60/40  (Equity / Fixed Income %)',
            'IVV':24,
            'ESGU':11,
            'EFG':8,
            'ESGE':7,
            'VLUE':3,
            'IXN':3,
            'IHI':3,
            'USMV':2,
            'LQD': 13,
            'IGSB': 6,
            'GOVT': 10,   
            'NEAR': 6,
            'SHYG': 6,
            'TLT':1,
            'fees':.0017,
        },

        {   'id':13,
            'company':'BlackRock',
            'name': '70/30  (Equity / Fixed Income %)',
            'IVV':24,
            'ESGU':17,
            'EFG':9,
            'ESGE':8,
            'VLUE':3,
            'IXN':4,
            'IHI':3,
            'USMV':3,
            'LQD': 10,
            'IGSB': 3,
            'GOVT': 8,   
            'NEAR': 4,
            'SHYG': 3,
            'TLT':1,
            'fees':.0018,
            
        },

         {   'id':14,
            'company':'BlackRock',
            'name': '80/20  (Equity / Fixed Income %)',
            'IVV':24,
            'ESGU':22,
            'EFG':11,
            'ESGE':9,
            'VLUE':4,
            'IXN':4,
            'IHI':4,
            'USMV':3,
            'LQD': 7,
            'IGSB': 2,
            'GOVT': 4,   
            'NEAR': 5,
            'TLT':1,
            'fees':.0019,
            
        },

         {   'id':15,
            'company':'BlackRock',
            'name': '90/10  (Equity / Fixed Income %)',
            'IVV':24,
            'ESGU':25,
            'EFG':13,
            'ESGE':10,
            'VLUE':5,
            'IXN':5,
            'IHI':5,
            'USMV':4,
            'LQD': 3,
            'GOVT': 4,   
            'NEAR': 2,
            'fees':.002,
            
        },

          {   'id':16,
            'company':'BlackRock',
            'name': '100/0  (Equity / Fixed Income %)',
            'IVV':25,
            'ESGU':25,
            'EFG':14,
            'ESGE':10,
            'VLUE':5,
            'IXN':5,
            'IHI':5,
            'USMV':4,
            'ITOT': 7,  
            'fees':.0019,
            
        },
 ]






# shows a single todo item and lets you delete a todo item
class SingleModel(Resource):
    def get(self, id):
        model = [model for model in models if model['id'] == id]
        if len(model) == 0:
            abort(404)
        return jsonify({"models": model}) 

# TodoList
# shows a list of all todos, and lets you POST to add new tasks
class Models(Resource):
    def get(self):
        return jsonify({'models':models})

